"""subscribers and reminder events

Revision ID: 67ddc5799c6f
Revises: 
Create Date: 2026-07-17 17:44:33.371744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67ddc5799c6f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscribers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('initial_attestation', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('unsubscribe_token', sa.String(length=64), nullable=False),
    sa.Column('attestation_text_version', sa.String(length=20), nullable=False),
    sa.Column('signup_ip', sa.String(length=64), nullable=True),
    sa.Column('signup_user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscribers_email'), 'subscribers', ['email'], unique=True)
    op.create_index(op.f('ix_subscribers_unsubscribe_token'), 'subscribers', ['unsubscribe_token'], unique=True)
    op.create_table('reminder_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subscriber_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('text_version', sa.String(length=20), nullable=False),
    sa.Column('response', sa.String(length=20), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('responded_ip', sa.String(length=64), nullable=True),
    sa.Column('responded_user_agent', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscribers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscriber_id', 'year', name='uq_reminder_subscriber_year')
    )
    op.create_index(op.f('ix_reminder_events_subscriber_id'), 'reminder_events', ['subscriber_id'], unique=False)
    op.create_index(op.f('ix_reminder_events_token'), 'reminder_events', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reminder_events_token'), table_name='reminder_events')
    op.drop_index(op.f('ix_reminder_events_subscriber_id'), table_name='reminder_events')
    op.drop_table('reminder_events')
    op.drop_index(op.f('ix_subscribers_unsubscribe_token'), table_name='subscribers')
    op.drop_index(op.f('ix_subscribers_email'), table_name='subscribers')
    op.drop_table('subscribers')
    # ### end Alembic commands ###
