"""subscriber cases

Revision ID: c5024cdcaeef
Revises: 67ddc5799c6f
Create Date: 2026-07-18 13:38:27.988892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5024cdcaeef'
down_revision: Union[str, None] = '67ddc5799c6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'subscribers',
        sa.Column('cases', sa.JSON(), nullable=False, server_default=sa.text("'[]'::json")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscribers', 'cases')
    # ### end Alembic commands ###
